server:
  port: 8001

spring:
  datasource:
    username: root
    password: 5436yinyuLONG
    url: jdbc:mysql://127.0.0.1:3306/api-gateshield?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml